# Generated by Django 3.2.12 on 2022-04-17 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0003_add_timestamp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'User',
                     'verbose_name_plural': 'Users'},
        ),
    ]
