repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    files: backend/
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    files: backend/
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    files: backend/
    hooks:
      - id: flake8
        args: [--config, 'backend/.flake8']

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.2'
    files: backend/
    hooks:
      - id: bandit
        args:
          - -lll
          - --severity-level high

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.3
    files: backend/
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.12.0'
    files: frontend/
    hooks:
    - id: eslint
      types: [ file ]
      types_or: [ javascript, jsx, ts, tsx, vue ]
      additional_dependencies:
      - '@vue/cli-plugin-eslint@4.5.0'
      - '@vue/eslint-config-prettier@6.0.0'
      - babel-eslint@10.1.0
      - eslint@6.7.2
      - prettier@2.2.1
      - eslint-plugin-prettier@3.3.1
      - eslint-plugin-vue@6.2.2
