version: '3.8'

services:
  api:
    ports:
      - "0.0.0.0:8000:8000"
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - ./backend:/app
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
  db:
    ports:
      - "5432:5432"
volumes:
  api:
  frontend:
