version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - backend/.env
  frontend:
    environment:
      VUE_APP_BASE_URL: http://api:8000
  db:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  api:
  database:
  frontend:
