version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - api
    environment:
      VUE_APP_BASE_URL: http://api:8000
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
#    healthcheck:
#      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
#      interval: 10s
#      timeout: 5s
#      retries: 5
volumes:
  api:
  database:
  frontend:
