# Generated by Django 3.2.12 on 2022-03-27 20:41

import uuid

import base.model_fields
import base.validators
import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('pk_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=news.models.image_directory_path,
                                            validators=[base.validators.validate_image_extension])),
                ('slug', base.model_fields.SanitizedCharField(blank=True, max_length=255)),
                ('name', base.model_fields.SanitizedCharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pk_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('short_description', models.CharField(max_length=256)),
                ('cover_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news',
                                                     to='news.imagecontent')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
            },
        ),
    ]
