# Generated by Django 3.2.12 on 2022-03-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news',
                                    to='news.imagecontent'),
        ),
    ]
