# Generated by Django 3.2.12 on 2022-04-17 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_add_timestamp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Article',
                     'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='imagecontent',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Image',
                     'verbose_name_plural': 'Images'},
        ),
    ]
