# Generated by Django 3.2.12 on 2022-04-24 20:09

import base.validators
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0006_imagecontent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='deleted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.ImageField(blank=True, upload_to=news.models.image_directory_path,
                                    validators=[base.validators.validate_image_extension]),
        ),
    ]
